const BASE="https://site.api.espn.com/apis/site/v2/sports/football/nfl";
export async function getScoreboard(){const r=await fetch(`${BASE}/scoreboard`,{next:{revalidate:900}});if(!r.ok)throw new Error("NFL schedule source unavailable");return r.json()}
export function parseScoreboardEvent(e){const c=e.competitions?.[0],cs=c?.competitors||[],h=cs.find(x=>x.homeAway==="home"),a=cs.find(x=>x.homeAway==="away");return{id:e.id,kickoff:e.date,week:e.week?.number,home:h?.team?.displayName,away:a?.team?.displayName,homeAbbr:h?.team?.abbreviation,awayAbbr:a?.team?.abbreviation,homeScore:Number(h?.score),awayScore:Number(a?.score),completed:Boolean(c?.status?.type?.completed),venue:c?.venue?.fullName||""}}
export async function getCurrentWeekBundle(){const d=await getScoreboard();return{year:d.season?.year||new Date().getFullYear(),week:d.week?.number||1,seasonType:d.season?.type||2,events:(d.events||[]).map(parseScoreboardEvent).filter(x=>x.home&&x.away)}}
export async function getSeasonScoreboard(year,seasonType=2){const r=await fetch(`${BASE}/scoreboard?dates=${year}&seasontype=${seasonType}&limit=1000`,{next:{revalidate:1800}});if(!r.ok)return[];const d=await r.json();return(d.events||[]).map(parseScoreboardEvent).filter(x=>x.home&&x.away)}
export async function getTeamSummary(eventId){try{const r=await fetch(`${BASE}/summary?event=${eventId}`,{next:{revalidate:1800}});if(!r.ok)return null;return r.json()}catch{return null}}
function readStat(stats,names){if(!Array.isArray(stats))return null;for(const name of names){const h=stats.find(s=>s?.name===name||s?.displayName===name||s?.label===name||s?.abbreviation===name);if(h){const raw=h.value??h.displayValue,num=Number(String(raw).replace(/[^0-9.-]/g,""));if(Number.isFinite(num))return num}}return null}
export function parseBoxscoreMetrics(summary){const out={};for(const t of summary?.boxscore?.teams||[]){const name=t?.team?.displayName;if(!name)continue;const s=t.statistics||[],yards=readStat(s,["totalYards","Total Yards"]),plays=readStat(s,["totalOffensivePlays","Total Plays","plays"]),turnovers=readStat(s,["turnovers","Turnovers"]);out[name]={totalYards:yards,plays,ypp:Number.isFinite(yards)&&Number.isFinite(plays)&&plays>0?yards/plays:null,turnovers,thirdPct:null,redPct:null}}return out}
export async function getInjuriesForTeam(teamAbbr){try{const r=await fetch(`${BASE}/teams/${teamAbbr}/injuries`,{next:{revalidate:1800}});if(!r.ok)return[];const d=await r.json();return d.injuries||d.items||[]}catch{return[]}}
